name: CI

on:
  pull_request:
    branches: ['main']
  merge_group:
    types: [checks_requested]

jobs:
  ci-check:
    name: CI Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-node@v4.2.0
        with:
          node-version: 22
          cache: 'npm'

      - run: npm install
      - run: npm run build
      - run: npm run format:check
      - run: npm run lint:check
