name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: ['main']
  merge_group:
    types: [checks_requested]

jobs:
  ci-check:
    name: CI Checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm install
      - run: npm build
      - run: npm format
      - run: npm lint
