name: RELEASE

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  release:
    name: Run semantic-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.RELEASE_PKEY }}

      - uses: actions/setup-node@v4.2.0
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci
      - run: npm run build
      - run: npm run format
      - run: npm run lint

      # Run semantic-release which will determine the next version, update package.json, create a Git tag & release, and publish to npm.
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
