name: RELEASE

on:
  release:
    types: [ published ]

jobs:
  release:
    name: Build and Publish NPM Package
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: actions/setup-node@v4.2.0
        with:
          node-version: 22
          cache: 'npm'

      - run: npm install
      - run: npm run build
      - run: npm run format
      - run: npm run lint

      - uses: JS-DevTools/npm-publish@v3.1.1
        with:
          access: 'public'
          token: ${{ secrets.NPM_TOKEN }}
